appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: af1vwB3vbLISPw2g3TN9AK6arzydhz1TUcWuahrR8LZEiExzi1KP6/gkjLDHa/Dk5Lz5CeZB4++cLlpqe+oKJ2AOO+PP+EP6tGs3qQJtaiUph2cZaS189KDh1AFnEVK4t3eQQoIhqu86nMihwL6evL2UTMQEKudrGS/flaVq4b8L05VpUrnAuMsbEMvOyQQm3JZpCC83mwveh9Ah9ucPYvQ77/ToPm3I/P5Yz8wvDiRFOMA3KI+vbrqmijIGArzCtKKJjvYP9UGRHO7EzJuN82brXxZpPaPzLfB4It7PgokUgmgKjXz4iCw9/wbqD8mfhP5tdnIWslBBshunvafgP48EBJEw9Dd3RKyzCqAY+PvcKDKbLn4fCOxMPRSEdM+HdjqbGUEQuBZcr+girgETy7eOkKhljzSIEcAuN0pWPkAY7m7dnHs/rbChI86IYpknI9U1F1+dQR3Ntp9TbTY7wi4KCcLdqR3y0huJ+742RC0MMduxAn4R4sjufaFwKk86pnD9HhcFK4l3bFwFCYDIxhVwc8j9XmMOjNT+nADWos2St4Tycr4bln8zwZ3Mty9se9dp5rxqnjtOZ3wAD7vp/fMyIvkHEbReH+IfTjx91yxQrRmSgeUCIHJcmT7WyB4eEodM1+uwniJe4ZJUxv0QO5bhDRg3u1ilG54DT8c7GHA=}
conda_forge_output_validation: true
