travis:
  secure:
    BINSTAR_TOKEN: cL/HtGafUiF6xKt0m3+EXUvw0I2NVZNwWhzOpw8TJxKjH4E/MxwQvvweqsFRmf46OBu+pjZ6cFjgMQCrS3XHttvw8XRAjjnhIUSPJ+p7qBbdHWBlP5BTHUCy/xiGyg15F1rkc8X3RIccmvTU11vokZJwwDQcbH04HIBT/Z/Nw1vr6n/G+HwKhQnjhpO+hSO01nAKf+Si7/HA4Gd5GhtHCbzMncKHRRo9CQZF9HEBg7GNmc0nU+3HL1/WzqA0cOJLNolQLUMMmD8HEcjx4A9DZ+GioK2Dn/2vnE1RLQZPMDKfQl+dOSjpWNXnizC/w0GrjW+68VHlg/GEXogzkFJHYQ/R4C4LlVCbpZL+5IRY0EabnyHXY52xdb8u9Fn8ITcWdjpkLx2fPKkUoCg2bJe8Fz6jW7qFvOCKczjdZlQYVYgQkiD1MDCSuSNJdp1W6yzGZMtosRaGcwG/1BwbeNeetcvH+VEKTDR6ghBDnYj/lEhT0dzn9bEkfbUY8Wc1IdpFofNMH4OP84iORm1/5oEP4O13LiF7bjxk7ynXXjNOU+AIwCzA3INVqnnoe+YbdNd6Yy+8C79n0hMd94mQMlrcPxtsdBSxidnwhIVGDcq81kW2Va2zW5dmQc3c36xXsr+EMrb7OXn3/QHT0sVgpCjDBpqEF6aHwS028nK5RI8U2us=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
