travis:
  secure:
    BINSTAR_TOKEN: Hbz0BRYtJ3GztpbsxxDF7u0d7+AktrvLMNetoVkXN78/O4GrJZyImCqMaX9ZW+/2CU40UpPbp2qcWZZMQzd8U5EVlE7eWF7M/xU0DdvEI/SZTVqmAOct+ruNhl8ErWneKsf2dJgLZhfHOeCWoFx2wn03iC0uU9xbBNTi0QKpb9V5VoaMMOqAQbQVcKsty9oHsUzEiyqh8fiwzx2d7HmjUVTV3mnTuEbLf7DXtR26S3Ouu1c40l0Urm7fbKNhtiZR5vqE8FH6hVa8axyUOan83cBc4C/Neq2QjDwkvvA0Qx561RN01FmsHKfCRLAX6BhNoGhu/CjOg55sqfCWWVkVzx+SR7t3OBR8geFf85NiSP0c05bafri8fYY8azfuXrTZjUfwT2OmoYOXl9F9XGZpUeIt+BtxtwMrbb0In7pZFHuTl2wlmleZ6of0ndryVX3SRNoU3TyEx3Jy4lw2hOkADFiibOJOnLYBS8w/qdxXEy5ev5MAUwcC3ZG1MGzihYrMM1qYCRFZXLmuORR6oGtQeXN+ta72oN5LO5C2HQiOidHJlykU2TOAn3KJsdGfPgE5C0AWkhYF9Qcy8sNiY6nk5wVzPxYBqffn8C6OEhFb1o5tQs6JiH74CsMv22L/dQ8FEvdY4vDH/MW3wY6x+zdNcd9JTSLHfk7iCuGIJ+HosQc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
